In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup


new=pd.DataFrame()

for j in range(1,6):

    url=f"https://school.careers360.com/schools/schools-in-india?page={j}"
    headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
    webpage=requests.get(url,headers).text
    
    soup=BeautifulSoup(webpage,'lxml')
    schools=soup.find_all('div', class_="schoolListing_card position-relative")
    
    name=[]
    fee=[]
    System=[]
    Place=[]
    rating=[]
    types=[]
    for i in schools:
        name.append(i.find('h2',class_='school_Name').text.strip())
        fee.append(i.find('div',class_="schoolList_Info d-flex align-items-center gap-1 flex-wrap mb-1").text.strip()[15:22])
        rating.append(i.find('div',class_='school-overview').text[19:24])
        System.append(i.find('span',class_='comma').text.strip())
        types.append((i.find_all('div', class_ = 'schoolList_Info d-flex align-items-center gap-1 flex-wrap mb-1')[1]).find_all('span')[0].text.strip())
    
    d={"NAME":name,
        "FEE":fee, 
        "System":System,
        "Place":Place,
        "Type":types,
        "Rating":rating}
    df = pd.DataFrame.from_dict(d, orient='index')
    df = df.T
    df.head()

    new=pd.concat([new,df],ignore_index=True)

In [2]:
new

,NAME,FEE,System,Place,Type,Rating
0,"Shri Ram Centennial School, Jaganpura","127,800",CBSE,None,Sr. Secondary/Higher Secondary School,AAAAA
1,"Vivek High School, Sector-38-B",,CBSE,None,Sr. Secondary/Higher Secondary School,AAAAA
2,"DAV Senior Secondary School (Lahore), Sector-8C",,CBSE,None,Sr. Secondary/Higher Secondary School,AAAAA
3,"Government Model Senior Secondary School, Sec...",682 (CB,CBSE,None,Sr. Secondary/Higher Secondary School,AAAAA
4,"Carmel Convent School, Sector 9B","30,090",CBSE,None,Sr. Secondary/Higher Secondary School,AAAAA
...,...,...,...,...,...,...
195,"Salwan Public School, Mayur Vihar Phase-III","88,241",CBSE,None,Sr. Secondary/Higher Secondary School,AAAA+
196,"N K Bagrodia Global School, Sector-17, Dwarka",,CBSE,None,Sr. Secondary/Higher Secondary School,AAAA+
197,"Delhi Public School, Gavier","170,530",CBSE,None,Sr. Secondary/Higher Secondary School,AAAA+
198,"Delhi Public School, kalali","125,075",CBSE,None,Sr. Secondary/Higher Secondary School,AAAA+
199,"Atmiya Vidya Mandir, Kamrej",,CBSE,None,Sr. Secondary/Higher Secondary School,AAAA+